image: docker.slock.it/build-images/node:10-alpine
stages:
- build
- package

# Job templates
build:
  stage: build
  tags:
  - short-jobs
  script:
  - cd client
  - sh /prepare.sh
  - npm install
  - CI=false 
  - npm run build
  - CI=true 
  artifacts:
    paths:
    - build/

docker-package:
  stage: package
  tags:
  - short-jobs
  dependencies:
    - build
  image: docker
  services:
  - docker:dind
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
  - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME $CI_REGISTRY_IMAGE:latest
  - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  - docker push $CI_REGISTRY_IMAGE:latest