image: docker.slock.it/build-images/node:10-alpine
stages:
- build
- package
- analyse
- deploy

# Job templates
build:
  stage: build
  tags:
  - short-jobs
  script:
  - cd client
  - sh /prepare.sh
  - npm install
  - CI=false 
  - npm run build
  - CI=true
  artifacts:
    paths:
    - client/build/

docker-package:
  stage: package
  tags:
  - short-jobs
  dependencies:
    - build
  image: docker
  services:
  - docker:dind
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
  - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME $CI_REGISTRY_IMAGE:latest
  - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  - docker push $CI_REGISTRY_IMAGE:latest

vulnerabilities:
  stage: analysis
  tags:
    - short-jobs
  dependencies:
    - docker-package
  allow_failure: true
  image: docker.slock.it/build-images/vulnerability-testing-tools
  script:
    - export TRIVY_AUTH_URL=$CI_REGISTRY
    - export TRIVY_USERNAME=gitlab-ci-token
    - export TRIVY_PASSWORD=$CI_JOB_TOKEN
    - trivy -f json -o vulnerability_analysis.json --exit-code 1 $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  artifacts:
    paths:
      - vulnerability_analysis.json

# Deployment template
.deploy-tmpl:
  stage: deploy
  tags:
    - short-jobs
  only:
    - /^v[0-9]+.[0-9]+.[0-9]?$/
  except:
    - branches
  allow_failure: false
  image: docker.slock.it/build-images/deployment
  services:
    - docker:dind
  script:
    - cd deployment
    - rancher -w up -f docker-compose.yml -d --prune -p -s in3-react-truffle-box -c --force-upgrade

# Production deployments
deploy-to-rancher:
  extends:
    - .deploy-tmpl